### ISSUE TITLE
Map Editor

### ISSUE THREAD

**Issue by Jaden1967** [Jaden1967/APP#5]

**Comment by Yilun-Sun** [comment]
# Map Editor basic setup

![image](https://user-images.githubusercontent.com/43896664/66141761-38c77780-e5d2-11e9-9245-e14cebfae53d.png)

**Comment by Yilun-Sun** [comment]
editcountry -add countryname continentname **_x-coordinate y-coordinate_**

**Comment by Yilun-Sun** [comment]
### need save map button

**Comment by Yilun-Sun** [comment]
if a continent removed, how could we arrange the countries in the continent before it been deleted?

**Comment by Yilun-Sun** [comment]
![image](https://user-images.githubusercontent.com/43896664/66264461-9971d280-e7d3-11e9-89b4-304c3c730379.png)

to be modified

**Comment by Jaden1967** [comment]
this template is the final version?

**Comment by Yilun-Sun** [comment]
> this template is the final version?

no, just a demo version, continents is ready to go, but still need to fix countries data structure

**Comment by Yilun-Sun** [comment]
Will push first build tonight

**Comment by Yilun-Sun** [comment]
a screen shot of map editor demo

![image](https://user-images.githubusercontent.com/43896664/66543620-eae7cd80-eb03-11e9-887a-92605d612430.png)
